<a href="https://colab.research.google.com/github/ShuimuZeng/Machine-learning/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def loss_function(y_real,y_pred):
  loss = 1/2*(y_real-y_pred)**2
  return loss

(y_real-y_pred)(y_real-y_pred)'-->(y_real-y_pred)*(-x)
-1(y_pred)'--> (wx+b)'--> -1(x)

In [3]:
# loss_function(np.array([1,2,3]),np.array([1,2,2]))
loss_function(1.45,2.01)

0.1567999999999999

In [4]:
# w = np.array([1,1.1,1.05])
def initialisation():
  w = np.random.rand(3)
  b = np.random.rand(1)
  lr = 0.0005
  return w,b,lr

In [5]:
# b = 1.05

In [6]:
# lr = 0.0005

In [7]:
# x = np.random.rand(3)
# # x

In [8]:
def predict(w,x,b):
 y_pred = np.dot(w,x)+b
 return y_pred

In [9]:
def gradiant_descendent(y_real,y_pred,w,x,b,lr):
  delta_w = (y_real-y_pred)*(-x)
  delta_b = (y_real-y_pred)*(-1)
  w = w - lr*delta_w
  b = b - lr*delta_b
  return delta_w,delta_b,w,b

In [10]:
def prepare_small_dataset():
  X = []
  for i in range(10):
    X.append(np.random.rand(3))
  y = np.random.rand(10)
  return X,y

In [11]:
prepare_small_dataset()

([array([0.89572433, 0.12926523, 0.04239712]),
  array([0.28736301, 0.86451661, 0.42369432]),
  array([0.80571314, 0.85519791, 0.62444669]),
  array([0.42347777, 0.44332559, 0.49053564]),
  array([0.45268284, 0.15654547, 0.73184671]),
  array([0.46206291, 0.21023897, 0.37726472]),
  array([0.56124276, 0.99243536, 0.27104494]),
  array([0.80550338, 0.66442802, 0.12660066]),
  array([0.3675353 , 0.52229374, 0.21954669]),
  array([0.46339518, 0.01419945, 0.48253387])],
 array([0.54849137, 0.54260441, 0.21285215, 0.95831199, 0.65601856,
        0.26644869, 0.52711255, 0.09827421, 0.52438334, 0.60901113]))

In [13]:
def train(epoch):
  X,y = prepare_small_dataset()
  w,b,lr = initialisation()
  for i in range(epoch):
    for j in range(len(X)):
      y_pred = predict(w,X[j],b)
      delta_w,delta_b,w,b = gradiant_descendent(y[j],y_pred,w,X[j],b,lr)
  return w,b

In [15]:
epoch_1 = 10
w_10,b_10 = train(epoch_1)
print(w_10,b_10)
epoch_2 = 100
w_100,b_100 = train(epoch_2)
w_100,b_100

[-0.00252499  0.25588192  0.35562993] [0.8181007]


(array([0.02889451, 0.15638256, 0.43915962]), array([0.55278004]))