<a href="https://colab.research.google.com/github/ShuimuZeng/Machine-learning/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def loss_function(y_real,y_pred):
  loss = 1/2*(y_real-y_pred)**2
  return loss

(y_real-y_pred)(y_real-y_pred)'-->(y_real-y_pred)*(-x)
-1(y_pred)'--> (wx+b)'--> -1(x)

In [ ]:
# loss_function(np.array([1,2,3]),np.array([1,2,2]))
loss_function(1.45,2.01)

0.1567999999999999

In [ ]:
# w = np.array([1,1.1,1.05])
def initialisation():
  w = np.random.rand(3)
  b = np.random.rand(1)
  lr = 0.0005
  return w,b,lr

In [ ]:
# def multivariable_init():

#   return 0

In [ ]:
# b = 1.05

In [ ]:
# lr = 0.0005

In [ ]:
# x = np.random.rand(3)
# # x

In [ ]:
def predict(w,x,b):
 y_pred = np.dot(w,x)+b
 return y_pred

In [ ]:
def gradiant_descendent(y_real,y_pred,w,x,b,lr):
  delta_w_array = np.zeros(3)
  for i in range(len(w)):
    delta_w_array[i]=(y_real-y_pred)*(-x[i])
  max_index = np.argmax(delta_w_array)
  delta_w = (y_real-y_pred)*(-x)
  delta_b = (y_real-y_pred)*(-1)
  #w = w - lr*delta_w
  w[max_index] = w[max_index] - lr*delta_w_array[max_index]
  b = b - lr*delta_b
  return delta_w,delta_b,w,b

In [ ]:
def prepare_small_dataset():
  X = []
  for i in range(10):
    X.append(np.random.rand(3))
  y = np.random.rand(10)
  return X,y

In [ ]:
prepare_small_dataset()

([array([0.38180832, 0.12960522, 0.42697939]),
  array([0.51647785, 0.79397123, 0.51261413]),
  array([0.95765924, 0.47975415, 0.60417215]),
  array([0.61396447, 0.27055192, 0.16853384]),
  array([0.02977036, 0.16189455, 0.58602637]),
  array([0.69462718, 0.74851085, 0.37653256]),
  array([0.52213283, 0.4875913 , 0.39597164]),
  array([0.33102335, 0.12302314, 0.78426057]),
  array([0.10784898, 0.9967045 , 0.66700721]),
  array([0.60809775, 0.52673686, 0.58082385])],
 array([0.24889441, 0.65417671, 0.17782332, 0.58717049, 0.62456095,
        0.28304899, 0.32983597, 0.9923912 , 0.91859148, 0.96084176]))

In [ ]:
def train(epoch):
  X,y = prepare_small_dataset()
  w,b,lr = initialisation()
  for i in range(epoch):
    for j in range(len(X)):
      y_pred = predict(w,X[j],b)
      # print(y_pred.shape)
      delta_w,delta_b,w,b = gradiant_descendent(y[j],y_pred,w,X[j],b,lr)
  return w,b

In [ ]:
epoch_1 = 10
w_10,b_10 = train(epoch_1)
print(w_10,b_10)
epoch_2 = 10000
w_100,b_100 = train(epoch_2)
w_100,b_100

<ipython-input-88-c2a7e76c3173>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  delta_w_array[i]=(y_real-y_pred)*(-x[i])


[0.37737709 0.95736184 0.44482069] [0.84655273]


(array([ 1.79918797, -1.63382451, -1.15056643]), array([1.19336476]))

In [ ]:
w2,b2,lr = initialisation()
w2,b2,lr
type(w2),len(w2)

(numpy.ndarray, 3)

In [ ]:
dataset2_X,dataset2_y = prepare_small_dataset()
len(dataset2_X[0])

3

In [ ]:
y_test_test = predict(w_100,dataset2_X[0],b_100)
loss_test_test = loss_function(dataset2_y[0],y_test_test)
loss_test_test

array([0.02685973])